# Generated by Django 4.2 on 2024-08-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('imageUrl', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('addressLine1', models.CharField(blank=True, max_length=100, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=100, null=True)),
                ('nationalTaxNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('primaryMobile', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hasServiceProvider', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.CharField(blank=True, default='False', max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('kinFirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('kinLastName', models.CharField(blank=True, max_length=100, null=True)),
                ('kinMobile', models.CharField(blank=True, max_length=100, null=True)),
                ('kinAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('kinemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('Projectid', models.CharField(blank=True, max_length=100, null=True)),
                ('providerId', models.CharField(blank=True, max_length=100, null=True)),
                ('contractorId', models.CharField(blank=True, max_length=100, null=True)),
                ('hasSchedule', models.CharField(blank=True, max_length=100, null=True)),
                ('centerAddressId', models.CharField(blank=True, max_length=100, null=True)),
                ('workingAddressId', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.CharField(max_length=100)),
                ('business_id', models.CharField(max_length=100)),
                ('flow', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('review pending', 'Review Pending'), ('registered', 'Registered'), ('completed', 'Completed'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('applied', 'Applied'), ('flow assigned', 'Flow Assigned')], default='registered', max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('createdBy', models.PositiveBigIntegerField(blank=True, null=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
