# Generated by Django 4.2 on 2024-08-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='Projectid',
            new_name='ProjectId',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='business_id',
            new_name='businessId',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='kinemail',
            new_name='kinEmail',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='middle_name',
            new_name='middleName',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='staff_id',
            new_name='staffId',
        ),
    ]
