# Generated by Django 4.2 on 2024-08-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_projectid_candidate_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childCandidates', to='candidate.candidate'),
        ),
    ]
